---
title: "final_project"
author: "Diego, Isaiah, Jake"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-libraries, message=FALSE}
library(tidyverse)
library(leaflet)
library(RColorBrewer)
library(socviz)
library(usmap)
library(maps)
library(cowplot)
```


```{r readingData, echo=FALSE, warning=FALSE, message=FALSE}
cardio <- read_csv2("data/cardio_train.csv")
vital <- read_csv("data/Data1.csv")
```

```{r cardioHandeling, echo=FALSE}
mycardio <- cardio %>%
  rename("ID" = id,
         "Age" = age,
         "Gender" = gender,
         "Height" = height,
         "Weight" = weight,
         "Systolic blood pressure" = ap_hi,
         "Diastolic blood pressure" = ap_lo,
         "Cholesterol" = cholesterol,
         "Glucose" = gluc,
         "Smoke" = smoke,
         "Alcohol" = alco,
         "Active" = active,
         "Cardio" = cardio)

mycardio <- mycardio %>%
  mutate(Age = as.numeric(Age)/365) %>%
  mutate(Gender = case_when(Gender == "1" ~ "Female", 
                            Gender == "2" ~ "Male")) %>%
  mutate(Weight = as.numeric(Weight)*2.205/10) %>%
  mutate(Smoke = case_when(Smoke == "0" ~ "No", 
                           Smoke == "1" ~ "Yes")) %>%
  mutate(Alcohol = case_when(Alcohol == "0" ~ "No", 
                             Alcohol == "1" ~ "Yes")) %>%
  mutate(Active = case_when(Active == "0" ~ "No", 
                            Active == "1" ~ "Yes")) %>%
  mutate(Cardio = case_when(Cardio == "0" ~ "No", 
                            Cardio == "1" ~ "Yes")) %>%
  mutate(Height = as.numeric(Height)/2.54) %>%
  mutate(HeightFeet = floor(Height/12)) %>%
  mutate(HeightInches = round(Height - (12*HeightFeet), 1)) %>%
  mutate(HeightLong = paste(HeightFeet,"'",HeightInches))

mycardio$HeightFeet <- NULL
mycardio$HeightInches <- NULL

mycardio <- mycardio %>%
  select(ID:Height, HeightLong, Weight:Cardio)

```

```{r lifestyleGraph}
percentLife %>%
  filter(Lifestyle == "Active" | Lifestyle == "Alcohol" | Lifestyle == "Smoke") %>%
  ggplot() +
  geom_bar(mapping = aes(x = Gender, y = percent, fill = Lifestyle), stat = "identity") +
  facet_wrap(~Lifestyle, scales = "free_y")

percentLife %>%
  filter(Lifestyle == "Cardio") %>%
  ggplot() +
  geom_bar(mapping = aes(x = Gender, y = percent, fill = percent), stat = "identity") +
  scale_fill_distiller(palette = "Spectral") +
  labs(title = "Percentage of Gender with Cardiovascular Disease")
```


```{r cardioFacet}
facetCardio <- mycardio %>%
  select(Gender, Smoke:Cardio) %>%
  gather("Lifestyle", "Occurance", -Gender) %>%
  group_by(Gender, Lifestyle, Occurance) %>%
  count()

actFe <- facetCardio %>%
  filter(Gender == "Female" & Lifestyle == "Active" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
alcFe <- facetCardio %>%
  filter(Gender == "Female" & Lifestyle == "Alcohol" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
cardFe <- facetCardio %>%
  filter(Gender == "Female" & Lifestyle == "Cardio" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
smoFe <- facetCardio %>%
  filter(Gender == "Female" & Lifestyle == "Smoke" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)

actMa <- facetCardio %>%
  filter(Gender == "Male" & Lifestyle == "Active" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
alcMa <- facetCardio %>%
  filter(Gender == "Male" & Lifestyle == "Alcohol" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
cardMa <- facetCardio %>%
  filter(Gender == "Male" & Lifestyle == "Cardio" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)
smoMa <- facetCardio %>%
  filter(Gender == "Male" & Lifestyle == "Smoke" & Occurance == "Yes") %>%
  mutate(percent = n/45530) %>%
  select(Gender, Lifestyle, percent)

percentLife <- bind_rows(actFe, actMa, alcFe, alcMa, cardFe, cardMa, smoFe, smoMa)
percentLife$Occurance <- NULL
```

```{r bloodpressureGraph}
mycolors <- c("green", "red")


mycardio %>%
  filter(`Diastolic blood pressure` < 200 & `Systolic blood pressure` < 300 & `Diastolic blood pressure` > 30 & `Systolic blood pressure` > 30) %>%
  filter(Weight < 500) %>%
  ggplot() +
  geom_point(mapping = aes(x = `Systolic blood pressure`,
                           y = `Diastolic blood pressure`,
                           color = Cardio),
             alpha = 0.1) +
  scale_color_manual(values = mycolors) +
  labs(title = "Blood Pressure with Cardiovascular Disease")

# mycardio %>%
#   filter(Cholesterol == "1" & Glucose == "1" & `Diastolic blood pressure` < 200 & `Systolic blood pressure` < 300 & `Diastolic blood pressure` > 30 & `Systolic blood pressure` > 30) %>%
#   filter(Weight < 500) %>%
#   ggplot() +
#   geom_point(mapping = aes(x = `Systolic blood pressure`,
#                            y = `Diastolic blood pressure`,
#                            color = Cardio),
#              alpha = 0.1) +
#   scale_color_manual(values = mycolors) +
#   labs(title = "Blood Pressure with Cardiovascular Disease")
```

```{r vitalHandling, echo=FALSE}
rate<- vital%>%
  select(GeoLocation,LocationAbbr,Topic,Data_Value_Type,Data_Value,Break_Out_Category,Break_Out) %>%
  mutate(GeoLocation = str_remove_all(GeoLocation, "\\("), 
                        GeoLocation = str_remove_all(GeoLocation, "\\)"),
         Topic=case_when(Topic=="Diseases of the Heart (Heart Disease)"~"Heart Disease",
                         Topic=="Acute Myocardial Infarction (Heart Attack)"~"Heart Attack",
                         TRUE~Topic)) %>% 
  separate(GeoLocation,into = c("Latitude", "Longitude"),  ",") %>% 
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude)) %>% 
  na.omit()
```

```{r vitalGraphs}
#average mortality rate for each state by topic
state_avg <- rate %>% 
  group_by(LocationAbbr,Topic,Data_Value_Type) %>% 
  summarise(avg=mean(Data_Value))

#top 5 states in mortality by topic
state_avg_highest<- state_avg %>% 
  group_by(Topic,Data_Value_Type) %>% 
  top_n(5,avg) %>% 
  arrange(Data_Value_Type,desc(avg))

#plot of the top 5 states in every topic 
state_avg_highest%>% 
  filter(Topic=="Heart Attack") %>% 
ggplot()+
geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Heart Attack",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))

state_avg_highest%>% 
  filter(Topic=="Stroke") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Stroke",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))


state_avg_highest%>% 
  filter(Topic=="Major Cardiovascular Disease") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Major Cardiovascular Diease",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))


state_avg_highest%>% 
  filter(Topic=="Heart Failure") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Heart Failure",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))

state_avg_highest%>% 
  filter(Topic=="Heart Diease") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Heart Diease",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))

state_avg_highest%>% 
  filter(Topic=="Coronary Heart Disease") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Data_Value_Type,ncol = 2,scales = "free")+
  labs(title = "Average Mortality from Coronary Heart Disease",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r vitalFacet}
#2 plots faceted by topic showing the highest age-standarized and crude average rates
state_avg_highest%>% 
  filter(Data_Value_Type=="Crude") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Topic,ncol = 2,scales = "free")+
  labs(title = "Average Crude Mortality Rate",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))

state_avg_highest%>% 
  filter(Data_Value_Type=="Age-Standardized") %>% 
  ggplot()+
  geom_col(aes(reorder(LocationAbbr,avg),avg,fill=LocationAbbr))+
  facet_wrap(~Topic,ncol = 3,scales = "free")+
  labs(title = "Average Age-Standardized Mortality Rate",
       x=element_blank())+
  guides(fill=FALSE)+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r vitalGender}
####Which gender has the highest average mortality rate for each topic####
#find the average mortality rate among genders for each topic
Gender_average <- rate%>% 
  filter(Break_Out_Category=="Gender") %>%
  select(-Break_Out_Category) %>% 
  rename(Gender = Break_Out) %>% 
  group_by(Topic,Gender,Data_Value_Type) %>% 
  summarise(avg=mean(Data_Value))

#Plot the average mortality for each gender by topic
Gender_average %>% 
  ggplot()+
  geom_col(aes(Gender,avg,fill=Data_Value_Type),position = "dodge")+
  facet_wrap(~Topic,scales = "free")+
  labs(title = "Average Mortality among Gender")+
  theme(plot.title = element_text(hjust = 0.5,size = 25))
```

```{r mapUSAvgDeathRate, echo=FALSE}
#Select relevant variables 
vitalGender <- vital%>%
  select(Year, Break_Out_Category,Break_Out, GeoLocation, Topic,LocationAbbr,
         HighConfidenceLimit,LowConfidenceLimit,Data_Value,Data_Value_Type) %>% 
  arrange(Topic) %>% 
  na.omit()
#Use only the gender break out
vitalGender <- vitalGender %>% filter(Break_Out_Category=="Gender") %>%
  select(-Break_Out_Category) %>% rename(Gender = Break_Out)
#Divide geolocation into latitude and longitude
vitalGender <- vitalGender%>% mutate(GeoLocation = str_remove_all(GeoLocation, "\\("), 
                                     GeoLocation = str_remove_all(GeoLocation, "\\)")) %>% 
  separate(GeoLocation,into = c("Latitude", "Longitude"),  ",") %>% 
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude)) %>% 
  na.omit()


#### map of the us for stroke avg death rate (heat map) ####
strokeM <- vitalGender %>% filter(Data_Value_Type=="Age-Standardized") %>%
  group_by(LocationAbbr) %>% summarise(avg_deathRate = mean(Data_Value)) %>% rename(state = LocationAbbr)

#create a data fram with the us states
us_states <- us_map("states")
#Rename abbr to state
us_states <- us_states %>% rename(state=abbr)
#create data frame with mortality rate for mapping
strokeMaleMap <- left_join(us_states, strokeM)
#find centroid and bind to death rate
centroid <- aggregate(data=strokeMaleMap,
                      cbind(x, y) ~ avg_deathRate, FUN=mean)
#plot avg  death rate in us state map
strokeMaleMap %>%
  ggplot(aes(x,y, group=group, fill=avg_deathRate)) + 
  geom_polygon(color = "darkgray", size = 0.5)+
  scale_fill_gradient(low = "orange", 
                      high = "purple",
                      na.value = "gray") +
  guides(fill= guide_legend(nrow=1)) +
  geom_text(mapping = aes(x,y, label=round(avg_deathRate)), color = "black",
            data = centroid,
            inherit.aes = FALSE )+
  theme_map()+
  coord_equal()+
  labs(title = " Average Death Rate - Age standarized", fill = "Rate per 100,000") +
  theme(plot.title = element_text(hjust=0.5),
        legend.position = "bottom")
```

```{r lifestyleJoinDeathRate, echo=FALSE}
#Relation between age groups and life styles and cardivascular disease

#Select relevant variables 
vitalAge <- vital%>%
  select(Year, Break_Out_Category,Break_Out, GeoLocation, Topic,LocationAbbr,
         HighConfidenceLimit,LowConfidenceLimit,Data_Value, Data_Value_Type) %>% 
  arrange(Topic) %>% 
  na.omit()
#prepare cardio data set
cardio_j <- cardio %>%
  rename("ID" = id,
         "Age" = age,
         "Gender" = gender,
         "Height" = height,
         "Weight" = weight,
         "Systolic blood pressure" = ap_hi,
         "Diastolic blood pressure" = ap_lo,
         "Cholesterol" = cholesterol,
         "Glucose" = gluc,
         "Smoke" = smoke,
         "Alcohol" = alco,
         "Active" = active,
         "Cardio" = cardio)
cardio_j <- cardio_j %>%
  mutate(Age = as.numeric(Age)/365) %>%
  mutate(Gender = case_when(Gender == "1" ~ "Female", 
                            Gender == "2" ~ "Male")) %>%
  mutate(Weight = as.numeric(Weight)*2.205/10)

#Use only age break out category
vitalAge <- vitalAge %>% filter(Break_Out_Category=="Age") %>%
  select(-Break_Out_Category) %>% rename(Age = Break_Out)

#Filter for age groups that match cardio data set and obtain mean death rate
vitalAgeRelevant <- vitalAge %>% filter(Data_Value_Type == "Crude",
                                        Age == "25-44"| Age == "45-64" | Age == "18-24") %>%
  group_by(Age) %>%
  mutate(`Death Rate` = mean(Data_Value)/1000) %>%
  distinct(Age, .keep_all = TRUE) %>% select(Age,`Death Rate`)

mycardioAgeGroup <- cardio_j %>%
  mutate(Age = if_else(condition = Age<44, true = "25-44", false ="45-64"))

mycardioAgeGroup <- mycardioAgeGroup %>% group_by(Age) %>%
  summarise(Cardio = mean(Cardio)*100,
            Alcohol = mean(Alcohol)*100,
            Active = mean(Active)*100,
            Smoke = mean(Smoke)*100)

vital_cardio_join_age <- left_join(vitalAgeRelevant,mycardioAgeGroup)

vital_cardio_join_plot <- vital_cardio_join_age %>%
  gather(Pct_category,Pavg, -Age)

vital_cardio_join_plot %>% ggplot()+
  geom_point(aes(Age, Pavg, color = Pct_category), size = 3)+
  geom_line(aes(Age, Pavg, color = Pct_category), linetype = "dotted") + 
  facet_wrap(~Pct_category, scales = "free") +
  labs(title = "Comparison of lifestyles with average death rates",
       x = "Age", y = "Average") + guides(color = FALSE) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r leafletMapAvgDeathRate, echo=FALSE}
#Select relevant variables
vital_avg_state_all <- vital%>%
  select(Year, Break_Out_Category,Break_Out, GeoLocation, Topic,LocationAbbr,
         HighConfidenceLimit,LowConfidenceLimit,Data_Value, Data_Value_Type) %>% 
  arrange(Topic) %>% 
  na.omit()

vital_avg_state_all <- vital_avg_state_all %>%
  group_by(LocationAbbr) %>% mutate(avg = mean(Data_Value)) %>%
  distinct(LocationAbbr, .keep_all = TRUE)
vital_avg_state_all <- vital_avg_state_all%>% mutate(GeoLocation = str_remove_all(GeoLocation, "\\("), 
                                     GeoLocation = str_remove_all(GeoLocation, "\\)")) %>% 
  separate(GeoLocation,into = c("Latitude", "Longitude"),  ",") %>% 
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude)) %>% 
  na.omit()

state_avg_leaflet <- rate %>% 
  filter(Data_Value_Type=="Age-Standardized",Topic!="Major Cardiovascular Disease") %>% 
  group_by(Longitude,Latitude,LocationAbbr,Topic) %>% 
  summarise(avg=mean(Data_Value)) %>% 
  mutate(pct=avg/100000*100)
state_avg_leaflet <- state_avg_leaflet %>% select(-pct) %>%
  spread(Topic, avg) %>% mutate(`Coronary Heart Disease` = round(`Coronary Heart Disease`,2),
                                `Heart Attack` = round(`Heart Attack`,2),
                                `Heart Disease` = round(`Heart Disease`,2),
                                `Heart Failure` = round(`Heart Failure`, 2),
                                `Stroke` = round(`Stroke`, 2))

state_label <- sprintf("<b>Average mortality rate in: %s</b><br />Coronary Heart Disease:  %s<br/ >Heart Attack: %s<br/ >Heart Disease: %s<br/ >Heart Failure: %s<br/ >Stroke: %s",
                       state_avg_leaflet$LocationAbbr,
                    state_avg_leaflet$`Coronary Heart Disease`,
                    state_avg_leaflet$`Heart Attack`,
                    state_avg_leaflet$`Heart Disease`,
                    state_avg_leaflet$`Heart Failure`,
                    state_avg_leaflet$`Stroke`) %>%
  lapply(htmltools::HTML)

state_avg_leaflet %>% leaflet(options = leafletOptions(zoomSnap=1)) %>%
  addTiles() %>% setView(-98.00,38.71,zoom=4) %>%
  addMarkers(~Longitude, ~Latitude, label = state_label, popup = state_label)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
